Problem statement 1:
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np

def gen_vander_matrix(inputarray, n):
    output_matrix = np.array([x**i for x in inputarray for i in range(n)]).reshape(inputarray.size,n)
    return output_matrix

inputvalue = np.array([1,2,3,4,5])
number_of_columns = 3
adv_matrix = gen_vander_matrix(inputvalue,number_of_columns)

print("The input array is:",inputvalue,"\n")
print("Number of columns in output matrix should be:",number_of_columns, "\n")
print("Output matrix:\n",adv_matrix)

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Output matrix:
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print("Moving average of:", a, " is\n",moving_average(a).round(1))

Moving average of: [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]  is
 [  5.    4.7   5.7   6.7   9.7  28.7  49.3  72.7  84.   93.3 116.3]
